#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const workerRoot = path.resolve(__dirname, "..");
const sourcePath = path.join(workerRoot, "frontend", "slider.js");
const outDir = path.join(workerRoot, "src", "generated");
const outPath = path.join(outDir, "slider-runtime.ts");

async function main() {
  const source = await fs.readFile(sourcePath, "utf8");
  const runtimeScript = source;

  const banner =
    "// AUTO-GENERATED FILE. DO NOT EDIT.\n" +
    "// Source: worker/frontend/slider.js\n" +
    "// Generated by: worker/scripts/build-slider.mjs\n\n";
  const output = `${banner}export const SLIDER_RUNTIME_SCRIPT = ${JSON.stringify(runtimeScript)};\n`;

  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(outPath, output, "utf8");
  console.log(`Generated ${path.relative(workerRoot, outPath)} (${runtimeScript.length} bytes, plain mode)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
